### PR TITLE
bookmarks cards

### PR DESCRIPTION
**Pull request by Traineratwot**
preview

Hi, I really like your project

And I want to offer you my implementation bookmark cards like `Terminus`

This page appears instead of greeting when there are no open tabs and there is at least one bookmark.

p.s

I think you can still add a button to call it, but I haven't figured out how to do it better yet

### CODE REVIEW

**Comment by zxdong262** [comment]
@Traineratwot 

Thank you for the support!

The idea make sense, user may want to click a bookmark since user already created bookmarks, but I think we should just put the existing bookmark tree list here, would be more consistant in UI/UX, so I can not accept this card list.

**Comment by loveyourvoice** [comment]
> @Traineratwot
> 
> Thank you for the support!
> 
> The idea make sense, user may want to click a bookmark since user already created bookmarks, but I think we should just put the existing bookmark tree list here, would be more consistant in UI/UX, so I can not accept this card list.

Hi, friend! You're wrong — this is a very convenient and appealing feature. You absolutely need to accept this request. Many users are switching from your product to Termius precisely because of this. Even though you offer free synchronization while Termius only provides it for a fee.

**Comment by theeye1980** [comment]
> @Traineratwot
> 
> Thank you for the support!
> 
> The idea make sense, user may want to click a bookmark since user already created bookmarks, but I think we should just put the existing bookmark tree list here, would be more consistant in UI/UX, so I can not accept this card list.

I join the request, as I also consider this a very necessary feature.

**Comment by dimitriytiho** [comment]
@Traineratwot is a good idea!

**Comment by prettyolgapo** [comment]
> @Traineratwot
> 
> Thank you for the support!
> 
> The idea make sense, user may want to click a bookmark since user already created bookmarks, but I think we should just put the existing bookmark tree list here, would be more consistant in UI/UX, so I can not accept this card list.

Hello, friends! The bookmarks suggested by @Traineratwot would really be useful for users, I'm sure.

**Comment by Traineratwot** [comment]
@zxdong262 
If I add a switch to the settings for my display mode and it is turned off by default.

I will also put all my code in a separate directory so that it does not interfere with you.
Will you accept the pull-request?

**Comment by zxdong262** [comment]
> @zxdong262 If I add a switch to the settings for my display mode and it is turned off by default.
> 
> I will also put all my code in a separate directory so that it does not interfere with you. Will you accept the pull-request?

Hi @Traineratwot, 

Currently I would not not accept the card list, at least for now, but still I agree with your idea that we could put a bookmark list when no sessions, so I would welcome a PR that add a list using existing bookmark list, if you are interested.

**Comment by infoitwork** [comment]
Thank you for creating this add-on. It has become more convenient to work with compared to the standard solution. Now everything is clearly visible, and there is a search function. Thank you again for your support.

**Pull request closed without merging**
