### PR TITLE
[feat] Support http proxy

### PR DESCRIPTION
**Pull request by luckyye**
add http proxy using http connect method

### CODE REVIEW

**Comment by zxdong262** [comment]
Great! @luckyye 

Can you add it to `src/client/components/setting-panel/setting.jsx`, there is a global proxy option need this too.

https://github.com/electerm/electerm/blob/f2243c46f7115d6c913784f3468dbc90f9eadac9/src/client/components/setting-panel/setting.jsx#L236-L237

**Comment by luckyye** [comment]
I think it is already added, can you see that?
`<Option value="0">http</Option>`

**Comment by zxdong262** [comment]
> I think it is already added, can you see that?
> `<Option value="0">http</Option>`

Oh, I missed it, sorry.

**Comment by zxdong262** [comment]
@luckyye Released new version with your PR https://github.com/electerm/electerm/releases/tag/v0.26.71

**Pull request merged**
