### PR TITLE
Publish to Windows Package Managar (WinGet)

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @electerm

### CODE REVIEW

**Comment by zxdong262** [comment]
@vedantmgoyal2009 Thank you! 
In https://github.com/electerm/electerm/blob/817c62ac87ff762ce5085b897dafbb64095206e5/.github/workflows/linux.yml#L59 here I used the github token, is it same token needed? If it is OK, you can change `WINGET_TOKEN` to `GITHUB_TOKEN`

**Comment by vedantmgoyal2009** [comment]
Actually the action will create a PR at winget-pkgs repository. If `GITHUB_TOKEN` is a personal access token from your account, then I can change, but if it isn't, then you need to create a PAT and admit as a repository secret.

**Comment by zxdong262** [comment]
> Actually the action will create a PR at winget-pkgs repository. If `GITHUB_TOKEN` is a personal access token from your account, then I can change, but if it isn't, then you need to create a PAT and add as a repository secret.

It is the default github token, I did not manually add this in secrets.

**Comment by zxdong262** [comment]
Also the https://github.com/electerm/winget-pkgs fork created

**Comment by vedantmgoyal2009** [comment]
Okay, then you'll need to add it👍

**Comment by zxdong262** [comment]
> Okay, then you'll need to add it👍

Done, the new personal access token with  public_repo scope added as `WINGET_TOKEN`

**Comment by vedantmgoyal2009** [comment]
@zxdong262 please give `workflow` scope to the token.

https://github.com/electerm/electerm/actions/runs/3076107754/jobs/4970033451#step:2:185

**Comment by vedantmgoyal2009** [comment]
cc @zxdong262

**Comment by zxdong262** [comment]
> @zxdong262 please give `workflow` scope to the token.
> 
> https://github.com/electerm/electerm/actions/runs/3076107754/jobs/4970033451#step:2:185

Done

**Pull request merged**
