### PR TITLE
Update winget-releaser & add dependabot

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@zxdong262 please regenerate and update the token. I guess it is expired.

**Comment by zxdong262** [comment]
> @zxdong262 please regenerate and update the token. I guess it is expired.

Got it, will do, thank you

**Comment by zxdong262** [comment]
@vedantmgoyal2009 Hi, winget build failed again, I checked the log, no idea why it failed, can you help with it?

**Comment by vedantmgoyal2009** [comment]
Please try re-running the workflow! I guess it should succeed now.

**Comment by zxdong262** [comment]
> Please try re-running the workflow! I guess it should succeed now.

Failed, seems same error message：https://github.com/electerm/electerm/actions/runs/4625867508/jobs/8232370627

**Comment by vedantmgoyal2009** [comment]
I guess, the GitHub PAT has expired, or you forgot to update the repository secret (https://github.com/electerm/electerm/settings/secrets/actions) after re-generating it.

**Comment by vedantmgoyal2009** [comment]
@russellbanks any idea what's going on here?

**Comment by vedantmgoyal2009** [comment]
@zxdong262 can you synchronize the fork manually by going to https://github.com/electerm/winget-pkgs? I guess it's failing because the fork has gotten behind with many commits. Please also re-run the latest workflow: https://github.com/electerm/electerm/actions/runs/5384539451.

**Comment by zxdong262** [comment]
Syned the fork, then rerun the workflow, get error: https://github.com/electerm/electerm/actions/runs/5384539451/jobs/9796826216, pull request created: https://github.com/microsoft/winget-pkgs/pull/110795

> @zxdong262 can you synchronize the fork manually by going to https://github.com/electerm/winget-pkgs? I guess it's failing because the fork has gotten behind with many commits. Please also re-run the latest workflow: https://github.com/electerm/electerm/actions/runs/5384539451.

**Comment by vedantmgoyal2009** [comment]
Finally, PR has been created. The error occurring now is a different one and will be fixed soon.

**Pull request merged**
